import 'package:flutter/material.dart';

class AppStrings {
  final Locale locale;
  AppStrings(this.locale);

  static const supportedLocales = <Locale>[
    Locale('en'), Locale('pt'), Locale('fr'), Locale('de'), Locale('it'), Locale('cs'), Locale('es'), Locale('ja'),
  ];

  static AppStrings of(BuildContext context) {
    final scope = context.dependOnInheritedWidgetOfExactType<_AppStringsScope>();
    return scope?.strings ?? AppStrings(const Locale('en'));
  }

  String get code => locale.languageCode;

  static const Map<String, Map<String, String>> _v = {
    'en': {'app_title':'NewsTube','home_search':'Search','home_favorites':'Favorites','search_hint':'Search videos or channels','search':'Search','channels':'Channels','videos':'Videos','favorites':'Favorites','favorite_channel':'Favorite channel','favorite_video':'Favorite video','remove_favorite':'Remove favorite','add_favorite':'Add favorite','no_results':'No results found.','no_favorites':'No favorites yet.','latest_favorites':'Latest videos from favorites','reload':'Reload','article':'Article','transcript':'Transcript','copy':'Copy','copied':'Text copied.','language':'Language','translate':'Translate','theme':'Theme','light':'Light','dark':'Dark','system':'System','interface_language':'Interface language','translate_language':'Translation language','choose_once_auto':'Choose once; translation will then be automatic','translate_done':'Translation completed','translate_failed':'Could not translate the text right now.','translating':'Translating...','view_original':'Show original','view_translation':'Show translation','grammar_fix':'Fix grammar','grammar_fixed':'Grammar corrected without changing meaning.','grammar_failed':'Could not correct the grammar right now.','correcting_grammar':'Correcting grammar...','article_title_translated':'Translated title','source':'Source','read':'Read','channel':'Channel','find_channels':'Find channels','enter_channel_name':'Enter the channel name','no_channel_found':'No channel found.','enter_search_term':'Type something to search.','loading':'Loading...','fetching_captions':'Fetching captions...','caption_label':'Caption','translate_banner':'The caption seems to be in “{caption}”, different from the system language (“{system}”). Do you want to translate it?','dont_remind':'Do not remind me','error_prefix':'Error','no_videos_for_channel':'No videos found for this channel.','load_more_failed':'Could not load more videos','render_error':'Error rendering the interface.','fatal_start':'Critical failure while starting the app.','caption_note':'Note: this mode only uses the video\'s own captions. If the video has no captions, it is not possible to generate text here.'},
    'pt': {'app_title':'NewsTube','home_search':'Buscar','home_favorites':'Favoritos','search_hint':'Buscar vídeos ou canais','search':'Buscar','channels':'Canais','videos':'Vídeos','favorites':'Favoritos','favorite_channel':'Canal favorito','favorite_video':'Vídeo favorito','remove_favorite':'Remover favorito','add_favorite':'Favoritar','no_results':'Nenhum resultado.','no_favorites':'Nenhum favorito ainda.','latest_favorites':'Últimos vídeos dos favoritos','reload':'Recarregar','article':'Artigo','transcript':'Transcrição','copy':'Copiar','copied':'Texto copiado.','language':'Idioma','translate':'Traduzir','theme':'Tema','light':'Claro','dark':'Escuro','system':'Sistema','interface_language':'Idioma da interface','translate_language':'Idioma da tradução','choose_once_auto':'Escolha uma vez; depois a tradução será automática','translate_done':'Tradução concluída','translate_failed':'Não foi possível traduzir o texto agora.','translating':'Traduzindo...','view_original':'Ver original','view_translation':'Ver tradução','grammar_fix':'Corrigir gramática','grammar_fixed':'Gramática corrigida sem alterar o sentido.','grammar_failed':'Não foi possível corrigir a gramática agora.','correcting_grammar':'Corrigindo gramática...','article_title_translated':'Título traduzido','source':'Fonte','read':'Lido','channel':'Canal','find_channels':'Buscar canais','enter_channel_name':'Digite o nome do canal','no_channel_found':'Nenhum canal encontrado.','enter_search_term':'Digite algo para buscar.','loading':'Carregando...','fetching_captions':'Buscando legendas...','caption_label':'Legenda','translate_banner':'A legenda parece estar em “{caption}”, diferente do idioma do sistema (“{system}”). Deseja traduzir?','dont_remind':'Não lembrar','error_prefix':'Erro','no_videos_for_channel':'Nenhum vídeo encontrado para este canal.','load_more_failed':'Não foi possível carregar mais vídeos','render_error':'Erro ao renderizar a interface.','fatal_start':'Falha crítica ao iniciar o aplicativo.','caption_note':'Observação: este modo usa apenas legendas do próprio vídeo. Se o vídeo não tiver legendas, não é possível gerar texto aqui.'},
    'fr': {'app_title':'NewsTube','home_search':'Recherche','home_favorites':'Favoris','search_hint':'Rechercher des vidéos ou des chaînes','search':'Rechercher','channels':'Chaînes','videos':'Vidéos','favorites':'Favoris','favorite_channel':'Chaîne favorite','favorite_video':'Vidéo favorite','remove_favorite':'Retirer des favoris','add_favorite':'Ajouter aux favoris','no_results':'Aucun résultat.','no_favorites':'Aucun favori pour le moment.','latest_favorites':'Dernières vidéos des favoris','reload':'Recharger','article':'Article','transcript':'Transcription','copy':'Copier','copied':'Texte copié.','language':'Langue','translate':'Traduire','theme':'Thème','light':'Clair','dark':'Sombre','system':'Système','interface_language':'Langue de l’interface','translate_language':'Langue de traduction','choose_once_auto':'Choisissez une fois ; ensuite la traduction sera automatique','translate_done':'Traduction terminée','translate_failed':'Impossible de traduire le texte pour le moment.','translating':'Traduction...','view_original':'Voir l’original','view_translation':'Voir la traduction','grammar_fix':'Corriger la grammaire','grammar_fixed':'Grammaire corrigée sans changer le sens.','grammar_failed':'Impossible de corriger la grammaire pour le moment.','correcting_grammar':'Correction grammaticale...','article_title_translated':'Titre traduit','source':'Source','read':'Lu','channel':'Chaîne','find_channels':'Rechercher des chaînes','enter_channel_name':'Entrez le nom de la chaîne','no_channel_found':'Aucune chaîne trouvée.','enter_search_term':'Saisissez quelque chose à rechercher.','loading':'Chargement...','fetching_captions':'Récupération des sous-titres...','caption_label':'Sous-titre','translate_banner':'Le sous-titre semble être en “{caption}”, différent de la langue du système (“{system}”). Voulez-vous traduire ?','dont_remind':'Ne plus rappeler','error_prefix':'Erreur','no_videos_for_channel':'Aucune vidéo trouvée pour cette chaîne.','load_more_failed':'Impossible de charger plus de vidéos','render_error':'Erreur lors du rendu de l’interface.','fatal_start':'Échec critique au démarrage de l’application.','caption_note':'Remarque : ce mode utilise uniquement les sous-titres de la vidéo elle-même. Si la vidéo n’a pas de sous-titres, il n’est pas possible de générer le texte ici.'},
    'de': {'app_title':'NewsTube','home_search':'Suche','home_favorites':'Favoriten','search_hint':'Videos oder Kanäle suchen','search':'Suchen','channels':'Kanäle','videos':'Videos','favorites':'Favoriten','favorite_channel':'Favorisierter Kanal','favorite_video':'Favorisiertes Video','remove_favorite':'Favorit entfernen','add_favorite':'Zu Favoriten','no_results':'Keine Ergebnisse.','no_favorites':'Noch keine Favoriten.','latest_favorites':'Neueste Videos aus den Favoriten','reload':'Neu laden','article':'Artikel','transcript':'Transkript','copy':'Kopieren','copied':'Text kopiert.','language':'Sprache','translate':'Übersetzen','theme':'Design','light':'Hell','dark':'Dunkel','system':'System','interface_language':'App-Sprache','translate_language':'Übersetzungssprache','choose_once_auto':'Einmal auswählen; danach erfolgt die Übersetzung automatisch','translate_done':'Übersetzung abgeschlossen','translate_failed':'Der Text konnte gerade nicht übersetzt werden.','translating':'Übersetzung läuft...','view_original':'Original anzeigen','view_translation':'Übersetzung anzeigen','grammar_fix':'Grammatik korrigieren','grammar_fixed':'Grammatik korrigiert, ohne den Inhalt zu ändern.','grammar_failed':'Die Grammatik konnte gerade nicht korrigiert werden.','correcting_grammar':'Grammatik wird korrigiert...','article_title_translated':'Übersetzter Titel','source':'Quelle','read':'Gelesen','channel':'Kanal','find_channels':'Kanäle suchen','enter_channel_name':'Kanalnamen eingeben','no_channel_found':'Kein Kanal gefunden.','enter_search_term':'Geben Sie etwas zum Suchen ein.','loading':'Wird geladen...','fetching_captions':'Untertitel werden geladen...','caption_label':'Untertitel','translate_banner':'Der Untertitel scheint auf „{caption}“ zu sein und unterscheidet sich von der Systemsprache („{system}“). Möchten Sie übersetzen?','dont_remind':'Nicht erinnern','error_prefix':'Fehler','no_videos_for_channel':'Für diesen Kanal wurden keine Videos gefunden.','load_more_failed':'Weitere Videos konnten nicht geladen werden','render_error':'Fehler beim Rendern der Oberfläche.','fatal_start':'Kritischer Fehler beim Starten der App.','caption_note':'Hinweis: Dieser Modus verwendet nur die eigenen Untertitel des Videos. Wenn das Video keine Untertitel hat, kann hier kein Text erzeugt werden.'},
    'it': {'app_title':'NewsTube','home_search':'Cerca','home_favorites':'Preferiti','search_hint':'Cerca video o canali','search':'Cerca','channels':'Canali','videos':'Video','favorites':'Preferiti','favorite_channel':'Canale preferito','favorite_video':'Video preferito','remove_favorite':'Rimuovi dai preferiti','add_favorite':'Aggiungi ai preferiti','no_results':'Nessun risultato.','no_favorites':'Nessun preferito per ora.','latest_favorites':'Ultimi video dai preferiti','reload':'Ricarica','article':'Articolo','transcript':'Trascrizione','copy':'Copia','copied':'Testo copiato.','language':'Lingua','translate':'Traduci','theme':'Tema','light':'Chiaro','dark':'Scuro','system':'Sistema','interface_language':'Lingua dell’interfaccia','translate_language':'Lingua di traduzione','choose_once_auto':'Scegli una volta; poi la traduzione sarà automatica','translate_done':'Traduzione completata','translate_failed':'Impossibile tradurre il testo ora.','translating':'Traduzione in corso...','view_original':'Vedi originale','view_translation':'Vedi traduzione','grammar_fix':'Correggi grammatica','grammar_fixed':'Grammatica corretta senza alterare il contenuto.','grammar_failed':'Impossibile correggere la grammatica ora.','correcting_grammar':'Correzione grammaticale...','article_title_translated':'Titolo tradotto','source':'Fonte','read':'Letto','channel':'Canale','find_channels':'Cerca canali','enter_channel_name':'Inserisci il nome del canale','no_channel_found':'Nessun canale trovato.','enter_search_term':'Digita qualcosa da cercare.','loading':'Caricamento...','fetching_captions':'Recupero sottotitoli...','caption_label':'Sottotitolo','translate_banner':'Il sottotitolo sembra essere in “{caption}”, diverso dalla lingua di sistema (“{system}”). Vuoi tradurre?','dont_remind':'Non ricordarmelo','error_prefix':'Errore','no_videos_for_channel':'Nessun video trovato per questo canale.','load_more_failed':'Impossibile caricare altri video','render_error':'Errore durante il rendering dell’interfaccia.','fatal_start':'Errore critico durante l’avvio dell’app.','caption_note':'Nota: questa modalità usa solo i sottotitoli del video. Se il video non ha sottotitoli, qui non è possibile generare testo.'},
    'cs': {'app_title':'NewsTube','home_search':'Hledat','home_favorites':'Oblíbené','search_hint':'Hledat videa nebo kanály','search':'Hledat','channels':'Kanály','videos':'Videa','favorites':'Oblíbené','favorite_channel':'Oblíbený kanál','favorite_video':'Oblíbené video','remove_favorite':'Odebrat z oblíbených','add_favorite':'Přidat do oblíbených','no_results':'Žádné výsledky.','no_favorites':'Zatím žádné oblíbené.','latest_favorites':'Nejnovější videa z oblíbených','reload':'Obnovit','article':'Článek','transcript':'Přepis','copy':'Kopírovat','copied':'Text zkopírován.','language':'Jazyk','translate':'Přeložit','theme':'Motiv','light':'Světlý','dark':'Tmavý','system':'Systém','interface_language':'Jazyk rozhraní','translate_language':'Jazyk překladu','choose_once_auto':'Vyberte jednou; pak bude překlad automatický','translate_done':'Překlad dokončen','translate_failed':'Text se nyní nepodařilo přeložit.','translating':'Překládání...','view_original':'Zobrazit originál','view_translation':'Zobrazit překlad','grammar_fix':'Opravit gramatiku','grammar_fixed':'Gramatika opravena bez změny obsahu.','grammar_failed':'Gramatiku se nyní nepodařilo opravit.','correcting_grammar':'Opravuji gramatiku...','article_title_translated':'Přeložený název','source':'Zdroj','read':'Přečteno','channel':'Kanál','find_channels':'Hledat kanály','enter_channel_name':'Zadejte název kanálu','no_channel_found':'Nebyl nalezen žádný kanál.','enter_search_term':'Zadejte něco k vyhledání.','loading':'Načítání...','fetching_captions':'Načítám titulky...','caption_label':'Titulky','translate_banner':'Zdá se, že titulky jsou v jazyce „{caption}“, který se liší od jazyka systému („{system}“). Chcete je přeložit?','dont_remind':'Nepřipomínat','error_prefix':'Chyba','no_videos_for_channel':'Pro tento kanál nebyla nalezena žádná videa.','load_more_failed':'Nepodařilo se načíst další videa','render_error':'Chyba při vykreslování rozhraní.','fatal_start':'Kritická chyba při spuštění aplikace.','caption_note':'Poznámka: tento režim používá pouze vlastní titulky videa. Pokud video nemá titulky, nelze zde vygenerovat text.'},
    'es': {'app_title':'NewsTube','home_search':'Buscar','home_favorites':'Favoritos','search_hint':'Buscar videos o canales','search':'Buscar','channels':'Canales','videos':'Videos','favorites':'Favoritos','favorite_channel':'Canal favorito','favorite_video':'Video favorito','remove_favorite':'Quitar favorito','add_favorite':'Agregar a favoritos','no_results':'Sin resultados.','no_favorites':'Todavía no hay favoritos.','latest_favorites':'Últimos videos de favoritos','reload':'Recargar','article':'Artículo','transcript':'Transcripción','copy':'Copiar','copied':'Texto copiado.','language':'Idioma','translate':'Traducir','theme':'Tema','light':'Claro','dark':'Oscuro','system':'Sistema','interface_language':'Idioma de la interfaz','translate_language':'Idioma de traducción','choose_once_auto':'Elige una vez; después la traducción será automática','translate_done':'Traducción completada','translate_failed':'No se pudo traducir el texto ahora.','translating':'Traduciendo...','view_original':'Ver original','view_translation':'Ver traducción','grammar_fix':'Corregir gramática','grammar_fixed':'Gramática corregida sin alterar el contenido.','grammar_failed':'No se pudo corregir la gramática ahora.','correcting_grammar':'Corrigiendo gramática...','article_title_translated':'Título traducido','source':'Fuente','read':'Leído','channel':'Canal','find_channels':'Buscar canales','enter_channel_name':'Escriba el nombre del canal','no_channel_found':'No se encontró ningún canal.','enter_search_term':'Escribe algo para buscar.','loading':'Cargando...','fetching_captions':'Obteniendo subtítulos...','caption_label':'Subtítulo','translate_banner':'Parece que el subtítulo está en “{caption}”, distinto del idioma del sistema (“{system}”). ¿Desea traducirlo?','dont_remind':'No recordar','error_prefix':'Error','no_videos_for_channel':'No se encontraron videos para este canal.','load_more_failed':'No se pudieron cargar más videos','render_error':'Error al renderizar la interfaz.','fatal_start':'Fallo crítico al iniciar la aplicación.','caption_note':'Nota: este modo solo usa los subtítulos del propio video. Si el video no tiene subtítulos, no es posible generar texto aquí.'},
    'ja': {'app_title':'NewsTube','home_search':'検索','home_favorites':'お気に入り','search_hint':'動画またはチャンネルを検索','search':'検索','channels':'チャンネル','videos':'動画','favorites':'お気に入り','favorite_channel':'お気に入りチャンネル','favorite_video':'お気に入り動画','remove_favorite':'お気に入りから削除','add_favorite':'お気に入りに追加','no_results':'結果がありません。','no_favorites':'お気に入りはまだありません。','latest_favorites':'お気に入りの最新動画','reload':'再読み込み','article':'記事','transcript':'文字起こし','copy':'コピー','copied':'テキストをコピーしました。','language':'言語','translate':'翻訳','theme':'テーマ','light':'ライト','dark':'ダーク','system':'システム','interface_language':'表示言語','translate_language':'翻訳言語','choose_once_auto':'一度選択すると、以後は自動で翻訳します','translate_done':'翻訳が完了しました','translate_failed':'現在、テキストを翻訳できません。','translating':'翻訳中...','view_original':'原文を表示','view_translation':'翻訳を表示','grammar_fix':'文法を修正','grammar_fixed':'内容を変えずに文法を修正しました。','grammar_failed':'現在、文法を修正できません。','correcting_grammar':'文法を修正中...','article_title_translated':'翻訳済みタイトル','source':'ソース','read':'既読','channel':'チャンネル','find_channels':'チャンネルを検索','enter_channel_name':'チャンネル名を入力','no_channel_found':'チャンネルが見つかりません。','enter_search_term':'検索語を入力してください。','loading':'読み込み中...','fetching_captions':'字幕を取得中...','caption_label':'字幕','translate_banner':'字幕の言語は「{caption}」で、システム言語「{system}」と異なるようです。翻訳しますか？','dont_remind':'今後表示しない','error_prefix':'エラー','no_videos_for_channel':'このチャンネルの動画が見つかりません。','load_more_failed':'さらに動画を読み込めませんでした','render_error':'画面の描画中にエラーが発生しました。','fatal_start':'アプリ起動時に重大なエラーが発生しました。','caption_note':'注: このモードでは動画自体の字幕のみを使用します。動画に字幕がない場合、ここでテキストを生成することはできません。'},
  };

  String t(String key,{Map<String,String> params=const {}}){
    final lang=_v[code]??_v['en']!;
    var value=lang[key]??_v['en']![key]??key;
    params.forEach((k,v){value=value.replaceAll('{$k}',v);});
    return value;
  }

  static Widget scope({required Locale locale,required Widget child})=>_AppStringsScope(strings: AppStrings(locale),child: child);
}
class _AppStringsScope extends InheritedWidget{final AppStrings strings;const _AppStringsScope({required this.strings,required super.child});@override bool updateShouldNotify(_AppStringsScope oldWidget)=>oldWidget.strings.code!=strings.code;}
